/*global systemDictionary:true */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
'use strict';

systemDictionary = {
    'mielecloudservice adapter settings': {
        'en': 'Adapter settings for mielecloudservice',
        'de': 'Adaptereinstellungen für mielecloudservice',
        'ru': 'Настройки адаптера для mielecloudservice',
        'pt': 'Configurações do adaptador para mielecloudservice',
        'nl': 'Adapterinstellingen voor mielecloudservice',
        'fr': "Paramètres d'adaptateur pour mielecloudservice",
        'it': "Impostazioni dell'adattatore per mielecloudservice",
        'es': 'Ajustes del adaptador para mielecloudservice',
        'pl': 'Ustawienia adaptera dla mielecloudservice',
        'zh-cn': 'mielecloudservice的适配器设置'
    },
    'option1': {
        'en': 'option1',
        'de': 'Option 1',
        'ru': 'Опция 1',
        'pt': 'Opção 1',
        'nl': 'Optie 1',
        'fr': 'Option 1',
        'it': 'opzione 1',
        'es': 'Opción 1',
        'pl': 'opcja 1',
        'zh-cn': '选项1'
    },
    'option2': {
        'en': 'option2',
        'de': 'Option 2',
        'ru': 'вариант 2',
        'pt': 'opção 2',
        'nl': 'Optie 2',
        'fr': 'Option 2',
        'it': 'opzione 2',
        'es': 'opcion 2',
        'pl': 'Opcja 2',
        'zh-cn': '选项2'
    }
};