/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Auto": {                                        "en": "Auto",                                            "de": "Auto",                                            "ru": "Автоматически",                                   "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto",                                            "pl": "Automatyczny",                                    "zh-cn": "汽车"},
    "Client_ID": {                                   "en": "API Client ID",                                   "de": "API-Client-ID",                                   "ru": "ID клиента API",                                  "pt": "ID do cliente da API",                            "nl": "API-client-ID",                                   "fr": "ID client API",                                   "it": "ID client API",                                   "es": "ID de cliente API",                               "pl": "ID klienta API",                                  "zh-cn": "API客户端ID"},
    "Client_ID_desc": {                              "en": "Your Miele API Client-ID",                        "de": "Ihre Miele API Client-ID",                        "ru": "Ваш Miele API Client-ID",                         "pt": "Seu ID de cliente da Miele API",                  "nl": "Uw Miele API-client-ID",                          "fr": "Votre numéro de client API Miele",                "it": "Il tuo ID client API Miele",                      "es": "Tu Miele API Client-ID",                          "pl": "Twój identyfikator klienta API Miele",            "zh-cn": "您的Miele API客户端ID"},
    "Client_secret": {                               "en": "API Client-secret",                               "de": "API-Client-Secret",                               "ru": "API Client-secret",                               "pt": "Segredo do cliente da API",                       "nl": "API Client-geheim",                               "fr": "API client-secret",                               "it": "Segreto client API",                              "es": "API cliente-secreto",                             "pl": "Tajny klient API",                                "zh-cn": "API客户端密钥"},
    "Client_secret_desc": {                          "en": "Your Miele API Client-Secret",                    "de": "Ihr Miele API Client-Secret",                     "ru": "Ваш Miele API Client-Secret",                     "pt": "Sua Miele API Client-Secret",                     "nl": "Uw Miele API-clientgeheim",                       "fr": "Votre secret client API Miele",                   "it": "Il segreto del client API Miele",                 "es": "Tu Miele API Client-Secret",                      "pl": "Twój tajemniczy klient API Miele",                "zh-cn": "您的Miele API客户端密钥"},
    "English": {                                     "en": "English",                                         "de": "Englisch",                                        "ru": "английский",                                      "pt": "Inglês",                                          "nl": "Engels",                                          "fr": "Anglais",                                         "it": "Inglese",                                         "es": "Inglés",                                          "pl": "język angielski",                                 "zh-cn": "英语"},
    "German": {                                      "en": "German",                                          "de": "Deutsch",                                         "ru": "Немецкий",                                        "pt": "alemão",                                          "nl": "Duitse",                                          "fr": "allemand",                                        "it": "Tedesco",                                         "es": "alemán",                                          "pl": "Niemiecki",                                       "zh-cn": "德语"},
    "Manual": {                                      "en": "Manual",                                          "de": "Manual",                                          "ru": "Вручную",                                         "pt": "Manual",                                          "nl": "Met de hand",                                     "fr": "Manuel",                                          "it": "Manuale",                                         "es": "Manual",                                          "pl": "podręcznik",                                      "zh-cn": "手册"},
    "Miele_Account": {                               "en": "Miele Account",                                   "de": "Miele-Konto",                                     "ru": "Miele Account",                                   "pt": "Conta Miele",                                     "nl": "Miele-account",                                   "fr": "Compte Miele",                                    "it": "Conto Miele",                                     "es": "Cuenta Miele",                                    "pl": "Konto Miele",                                     "zh-cn": "Miele帐户"},
    "Miele_Account_desc": {                          "en": "Your Miele App-Account (usually you eMail)",      "de": "Ihr Miele App-Account (in der Regel ihre eMail)", "ru": "Ваша учетная запись в приложении Miele (обычно вы пишете по электронной почте)", "pt": "Seu Miele App-Account (normalmente você recebe e-mail)", "nl": "Uw Miele-app-account (meestal e-mail)",           "fr": "Votre compte Miele App (habituellement vous envoyez un e-mail)", "it": "Il tuo account App Miele (di solito la tua e-mail)", "es": "Tu cuenta de la aplicación Miele (normalmente tu correo electrónico)", "pl": "Twoje konto aplikacji Miele (zazwyczaj e-mail)",  "zh-cn": "您的Miele App-Account（通常是您的电子邮件）"},
    "Miele_pwd": {                                   "en": "Miele Password",                                  "de": "Miele Passwort",                                  "ru": "Miele Password",                                  "pt": "Senha Miele",                                     "nl": "Miele-wachtwoord",                                "fr": "Miele Password",                                  "it": "Password Miele",                                  "es": "Contraseña de Miele",                             "pl": "Hasło Miele",                                     "zh-cn": "Miele密码"},
    "Miele_pwd_desc": {                              "en": "Your Miele App-Account Password",                 "de": "Ihr Miele App-Account Passwort",                  "ru": "Пароль вашего аккаунта Miele",                    "pt": "Sua senha da Miele App-Account",                  "nl": "Het wachtwoord van uw Miele-app-account",         "fr": "Votre mot de passe du compte de l'application Miele", "it": "La password dell'account app Miele",              "es": "Su aplicación Miele-Contraseña de cuenta",        "pl": "Twoje hasło do konta aplikacji Miele",            "zh-cn": "您的Miele应用帐户密码"},
    "My select": {                                   "en": "My select",                                       "de": "Meine Auswahl",                                   "ru": "Выбор",                                           "pt": "Meu selecionado",                                 "nl": "Mijn select",                                     "fr": "Mon choix",                                       "it": "La mia selezione",                                "es": "Mi seleccion",                                    "pl": "Mój wybór",                                       "zh-cn": "我的选择"},
    "locale": {                                      "en": "API Response language",                           "de": "API-Sprache",                                     "ru": "Автоматически",                                   "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto",                                            "pl": "Język odpowiedzi API",                            "zh-cn": "API响应语言"},
    "locale_desc": {                                 "en": "Language the Miele-API should respond in",        "de": "Sprache in der die API antwortet.",               "ru": "Автоматически",                                   "pt": "Auto",                                            "nl": "Auto",                                            "fr": "Auto",                                            "it": "Auto",                                            "es": "Auto",                                            "pl": "Język, w którym powinien reagować interfejs API Miele", "zh-cn": "Miele-API应该响应的语言"},
    "on save adapter restarts with new config immediately": {"en": "on save adapter restarts with new config immediately", "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.", "ru": "При сохранении настроек адаптера он сразу же перезапускается", "pt": "no adaptador de salvar reinicia com nova configuração imediatamente", "nl": "on save-adapter wordt onmiddellijk opnieuw opgestart met nieuwe config", "fr": "sur l'adaptateur de sauvegarde redémarre avec la nouvelle config immédiatement", "it": "su save adapter si riavvia immediatamente con la nuova configurazione", "es": "en el adaptador de guardar se reinicia con nueva configuración de inmediato", "pl": "na adapterze zapisu restartuje się natychmiast z nową konfiguracją", "zh-cn": "保存适配器立即重新启动新配置"},
    "template adapter settings": {                   "en": "template adapter settings",                       "de": "Beispiel",                                        "ru": "Пример",                                          "pt": "configurações do adaptador de modelo",            "nl": "sjabloon-adapterinstellingen",                    "fr": "paramètres de l'adaptateur de modèle",            "it": "impostazioni dell'adattatore del modello",        "es": "configuración del adaptador de plantilla",        "pl": "ustawienia adaptera szablonu",                    "zh-cn": "模板适配器设置"},
    "test1": {                                       "en": "Test 1",                                          "de": "Test 1",                                          "ru": "Тест 1",                                          "pt": "Teste 1",                                         "nl": "Test 1",                                          "fr": "Test 1",                                          "it": "Test 1",                                          "es": "Prueba 1",                                        "pl": "Test 1",                                          "zh-cn": "测试1"},
    "test2": {                                       "en": "Test 2",                                          "de": "Test 2",                                          "ru": "Тест 2",                                          "pt": "Teste 2",                                         "nl": "Test 2",                                          "fr": "Test 2",                                          "it": "Test 2",                                          "es": "Prueba 2",                                        "pl": "Test 2",                                          "zh-cn": "测试2"},
};